# Generated by Django 5.2.8 on 2025-11-27 12:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Corredor')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Pessoa de Contato')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='Endereço')),
                ('actif', models.BooleanField(blank=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('USER', 'Usuário Comum')], default='USER', max_length=10, verbose_name='Papel no Sistema')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.categorie', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nome do Depósito')),
                ('localisation', models.TextField(blank=True, verbose_name='Localização')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_geridos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Depósito')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Estante')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etageres', to='api.corredor')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
                'unique_together': {('numero', 'corredor')},
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('unite', models.CharField(max_length=20, verbose_name='Unidade')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('stock_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estoque Máximo')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Unitário')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='api.categorie')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='api.fournisseur')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Nível')),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='api.etagere')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'unique_together': {('numero', 'etagere')},
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emplacement', to='api.niveau')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
            },
        ),
        migrations.CreateModel(
            name='ProjetChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('localisation', models.TextField(blank=True, verbose_name='Localização')),
                ('pilier', models.CharField(choices=[('PILAR1', 'Pilar 1'), ('PILAR2', 'Pilar 2'), ('PILAR3', 'Pilar 3')], max_length=20, verbose_name='Pilar')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Término')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Projeto / Canteiro',
                'verbose_name_plural': 'Projetos / Canteiros',
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mvt', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('type_mvt', models.CharField(choices=[('ENTREE', 'Entrada'), ('SORTIE', 'Saída'), ('TRANSFERT', 'Transferência'), ('RETOUR', 'Devolução')], max_length=10, verbose_name='Tipo')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('raison', models.TextField(blank=True, verbose_name='Motivo / Observação')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_demandes', to=settings.AUTH_USER_MODEL)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.entrepot')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.materiel')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projetchantier')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'ordering': ['-date_mvt'],
            },
        ),
        migrations.AddField(
            model_name='entrepot',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots', to='api.projetchantier', verbose_name='Projeto Associado'),
        ),
        migrations.CreateModel(
            name='DemandeLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Rascunho'), ('EN_ATTENTE', 'Pendente'), ('APPROUVEE', 'Aprovada'), ('REFUSEE', 'Recusada'), ('LIVREE', 'Entregue')], default='BROUILLON', max_length=15, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Justificativa')),
                ('raison_refus', models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projetchantier')),
            ],
            options={
                'verbose_name': 'Pedido de Material',
                'verbose_name_plural': 'Pedidos de Materiais',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código da Zona')),
                ('nom', models.CharField(max_length=50, verbose_name='Nome da Zona')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.entrepot')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'unique_together': {('code', 'entrepot')},
            },
        ),
        migrations.AddField(
            model_name='corredor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredors', to='api.zone'),
        ),
        migrations.CreateModel(
            name='DemandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField(verbose_name='Qtd Pedida')),
                ('quantite_approuvee', models.PositiveIntegerField(default=0, verbose_name='Qtd Aprovada')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.demandelot')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materiel')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'unique_together': {('lot', 'materiel')},
            },
        ),
        migrations.CreateModel(
            name='StockEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emplacement', verbose_name='Localização Física')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.entrepot')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.materiel')),
            ],
            options={
                'verbose_name': 'Estoque no Depósito',
                'verbose_name_plural': 'Estoques nos Depósitos',
                'unique_together': {('materiel', 'entrepot', 'emplacement')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='corredor',
            unique_together={('numero', 'zone')},
        ),
    ]
