# Generated by Django 5.2.8 on 2025-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='diametre_nominal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Diâmetro Nominal (mm)'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materiais/', verbose_name='Foto do Material'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='pression_nominal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pressão Nominal'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='type_materiau',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Material'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='usage_typique',
            field=models.CharField(blank=True, help_text='ex: Extension réseau, Regard avec cage, Chemin de câbles', max_length=200, verbose_name='Uso Típico'),
        ),
    ]
