# Generated by Django 5.2.8 on 2025-12-11 09:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_materiel_diametre_nominal_materiel_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeitem',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emplacement'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur'),
        ),
        migrations.AddField(
            model_name='stockentrepot',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projetchantier'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('m', 'Metro'), ('kg', 'Quilo'), ('un', 'Unidade'), ('lot', 'Lote')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('changes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'Pendente'), ('LIVREE', 'Entregue')], max_length=20)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materiel')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.ManyToManyField(through='api.CommandeItem', to='api.materiel'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga')], max_length=20)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur')),
                ('mouvman', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mouvement')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('date_fabrication', models.DateField(null=True)),
                ('date_expiration', models.DateField(null=True)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('STOCK_BA', 'Stock Ba'), ('DEMANN_APWOUVE', 'Demann Apwouve')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportMouvman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('mouvman_entrees', models.PositiveIntegerField(default=0)),
                ('mouvman_sorties', models.PositiveIntegerField(default=0)),
                ('stock_initial', models.PositiveIntegerField()),
                ('stock_final', models.PositiveIntegerField()),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materiel')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projetchantier')),
            ],
            options={
                'verbose_name': 'Rapò Mouvman',
                'verbose_name_plural': 'Rapò Mouvman yo',
            },
        ),
    ]
