# Generated by Django 5.2.8 on 2025-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_demandeitem_emplacement_mouvement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('lot', 'Lote'), ('m', 'Metro'), ('kg', 'Quilo'), ('un', 'Unidade')], max_length=20, verbose_name='Unidade'),
        ),
    ]
