# Generated by Django 5.2.8 on 2025-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_materiel_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('m', 'Metro'), ('lot', 'Lote'), ('kg', 'Quilo')], max_length=20, verbose_name='Unidade'),
        ),
    ]
