# Generated by Django 5.2.8 on 2026-01-13 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_materiel_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('lot', 'Lote'), ('kg', 'Quilo'), ('m', 'Metro'), ('un', 'Unidade')], max_length=20, verbose_name='Unidade'),
        ),
    ]
