# Generated by Django 5.2.8 on 2026-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_materiel_prix_unitaire_alter_materiel_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='pression_nominal',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Pressão Nominal'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('m', 'Metro'), ('kg', 'Quilo'), ('lot', 'Lote')], max_length=20, verbose_name='Unidade'),
        ),
    ]
