# Generated by Django 5.2.8 on 2026-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_materiel_pression_nominal_alter_materiel_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='type_materiau',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('lot', 'Lote'), ('kg', 'Quilo'), ('m', 'Metro')], max_length=20, verbose_name='Unidade'),
        ),
    ]
