# Generated by Django 5.2.8 on 2026-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_materiel_type_materiau_alter_materiel_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='diametre_nominal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Diâmetro Nominal (mm)'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='pression_nominal',
            field=models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Pressão Nominal'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type_materiau',
            field=models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('m', 'Metro'), ('lot', 'Lote'), ('kg', 'Quilo'), ('un', 'Unidade')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='usage_typique',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Uso Típico'),
        ),
    ]
