# Generated by Django 5.2.8 on 2026-01-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_materiel_diametre_nominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('lot', 'Lote'), ('m', 'Metro')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.entrepot'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.materiel'),
        ),
    ]
