# Generated by Django 5.2.8 on 2026-01-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_materiel_unite_alter_mouvement_entrepot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('m', 'Metro'), ('lot', 'Lote')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('USER', 'Usuário Comum'), ('CONSULTATION', 'Consulta')], default='USER', max_length=20, verbose_name='Papel no Sistema'),
        ),
    ]
