# Generated by Django 5.2.8 on 2026-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_materiel_unite_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandelot',
            name='is_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('kg', 'Quilo'), ('lot', 'Lote'), ('un', 'Unidade'), ('m', 'Metro')], max_length=20, verbose_name='Unidade'),
        ),
    ]
