# Generated by Django 5.2.8 on 2026-01-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_demandelot_is_consultation_alter_materiel_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Famille')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, default='📦', max_length=10, verbose_name='Icone(emoji)')),
                ('ordre', models.PositiveBigIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Famille de Materiaux',
                'verbose_name_plural': 'Familles de Materiaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['famille', 'nom'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('m', 'Metro'), ('lot', 'Lote'), ('un', 'Unidade'), ('kg', 'Quilo')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.famille', verbose_name='Famille'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('famille', 'nom')},
        ),
    ]
