# Generated by Django 5.2.8 on 2026-01-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_famille_alter_categorie_options_alter_categorie_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['code'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AddField(
            model_name='materiel',
            name='entrepot_principal',
            field=models.ForeignKey(blank=True, help_text='Depot ou ce materiel est priclipalement stocke', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_principios', to='api.entrepot', verbose_name='Depot Principal'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='pilier',
            field=models.CharField(choices=[('TODOS', 'Todos os Pilares'), ('PILAR1', 'Pilar 1'), ('PILAR3', 'Pilar 3'), ('PILAR2', 'Pilar 2')], default='TOUS', help_text='Pilar auquel ce matériel est affecté', max_length=10, verbose_name='Pilar'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('m', 'Metro'), ('lot', 'Lote'), ('kg', 'Quilo')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['code', 'description'], name='api_materie_code_b3defc_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['pilier', 'entrepot_principal'], name='api_materie_pilier_f31406_idx'),
        ),
    ]
