# Generated by Django 5.2.8 on 2026-01-26 08:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_materiel_options_materiel_entrepot_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='code',
            field=models.CharField(help_text='Code court et lisible (ex: PLB, ELEC, INST)', max_length=10, null=True, unique=True, verbose_name='Code Famille'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='pilier',
            field=models.CharField(choices=[('PILAR3', 'Pilar 3'), ('PILAR1', 'Pilar 1'), ('TODOS', 'Todos os Pilares'), ('PILAR2', 'Pilar 2')], default='TOUS', help_text='Pilar auquel ce matériel est affecté', max_length=10, verbose_name=api.models.Entrepot),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('un', 'Unidade'), ('lot', 'Lote'), ('kg', 'Quilo'), ('m', 'Metro')], max_length=20, verbose_name='Unidade'),
        ),
    ]
