# Generated by Codex on 2026-01-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_famille_code_alter_materiel_pilier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeitem',
            name='entrepot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='demande_items',
                to='api.entrepot',
            ),
        ),
    ]
