# Generated by Codex on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_demandeitem_entrepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandelot',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, null=True, verbose_name='Referencia'),
        ),
    ]
