# Generated by Codex on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mouvement_demande_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='usage_type',
            field=models.CharField(
                choices=[('PRET', 'Pret'), ('INSTALL', 'Install')],
                default='INSTALL',
                max_length=10,
                verbose_name='Tipo de Uso',
            ),
        ),
        migrations.AddField(
            model_name='stockentrepot',
            name='status',
            field=models.CharField(
                choices=[
                    ('DISPONIVEL', 'Disponivel'),
                    ('EMPRESTADO', 'Emprestado'),
                    ('A_INSTALAR', 'A instalar'),
                    ('INSTALADO', 'Instalado'),
                ],
                default='DISPONIVEL',
                max_length=20,
                verbose_name='Estado',
            ),
        ),
        migrations.AddField(
            model_name='stockentrepot',
            name='data_retorno_prevista',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Data Retorno Prevista',
            ),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='code',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name='Código',
            ),
        ),
    ]

