# Generated by Codex on 2026-02-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_materiel_usage_type_stock_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockentrepot',
            unique_together={('materiel', 'entrepot')},
        ),
    ]

