# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_stockentrepot_unique_material_entrepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nome')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenome')),
                ('entreprise', models.CharField(max_length=150, verbose_name='Empresa')),
                ('fonction', models.CharField(max_length=150, verbose_name='Funcao')),
            ],
            options={
                'verbose_name': 'Utilisateur Final',
                'verbose_name_plural': 'Utilisateurs Finals',
            },
        ),
    ]

