# Generated by Codex on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_utilisateurfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='famille',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='zones',
                to='api.famille',
                verbose_name='Famille',
            ),
        ),
    ]

