# Generated by Django 5.2.8 on 2026-02-12 07:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_zone_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='pilier',
            field=models.CharField(choices=[('PILAR2', 'Pilar 2'), ('PILAR3', 'Pilar 3'), ('PILAR1', 'Pilar 1'), ('TODOS', 'Todos os Pilares')], default='TOUS', help_text='Pilar auquel ce matériel est affecté', max_length=10, verbose_name=api.models.Entrepot),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('lot', 'Lote'), ('un', 'Unidade'), ('m', 'Metro'), ('kg', 'Quilo')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='utilisateurfinal',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='utilisateurfinal',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prenome'),
        ),
    ]
