# Generated by Codex on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_zone_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandelot',
            name='demandeur_reel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='demandes',
                to='api.utilisateurfinal',
                verbose_name='Demandeur Real',
            ),
        ),
    ]

