# Generated by Django 5.2.8 on 2026-02-12 07:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_materiel_pilier_alter_materiel_unite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='pilier',
            field=models.CharField(choices=[('TODOS', 'Todos os Pilares'), ('PILAR3', 'Pilar 3'), ('PILAR2', 'Pilar 2'), ('PILAR1', 'Pilar 1')], default='TOUS', help_text='Pilar auquel ce matériel est affecté', max_length=10, verbose_name=api.models.Entrepot),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='unite',
            field=models.CharField(choices=[('lot', 'Lote'), ('un', 'Unidade'), ('kg', 'Quilo'), ('m', 'Metro')], max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='utilisateurfinal',
            name='fonction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Funcao'),
        ),
    ]
