# Generated by Codex on 2026-02-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_materiel_pilier_alter_materiel_unite_and_more'),
        ('api', '0022_demandelot_demandeur_reel'),
        ('api', '0023_alter_materiel_pilier_alter_materiel_unite_and_more'),
    ]

    operations = []

