# Generated by Django 5.2.8 on 2026-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pedidoformulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoformulario',
            name='tipo_fluxo',
            field=models.CharField(choices=[('INSTALACAO', 'Instalacao'), ('EMPRESTIMO', 'Empréstimo'), ('COMPRAS', 'Compras'), ('TRANSFERENCIA', 'Transferencia')], default='INSTALACAO', max_length=15),
        ),
    ]
