# Generated by Django 5.2.8 on 2026-02-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pedidoformulario_tipo_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoformulario',
            name='entrepot_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulários_destino', to='api.entrepot'),
        ),
        migrations.AddField(
            model_name='pedidoformulario',
            name='entrepot_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulários_origem', to='api.entrepot'),
        ),
    ]
