# Generated by Django 5.2.8 on 2026-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_pedidoformulario_entrepot_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeitem',
            name='comentario_recebimento',
            field=models.TextField(blank=True, verbose_name='Comentário de Recebimento'),
        ),
        migrations.AddField(
            model_name='demandeitem',
            name='data_necessaria',
            field=models.DateField(blank=True, null=True, verbose_name='Data Necessária'),
        ),
        migrations.AddField(
            model_name='demandeitem',
            name='estado_recebimento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFORME', 'Em conformidade'), ('AVARIA', 'Com avaria'), ('INCOMPLETO', 'Incompleto')], default='PENDENTE', max_length=20, verbose_name='Estado de Recebimento'),
        ),
        migrations.AddField(
            model_name='demandeitem',
            name='quantite_entregue',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd Entregue'),
        ),
        migrations.AddField(
            model_name='pedidoformulario',
            name='estado_recebimento_geral',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Em conformidade'), ('AVARIA', 'Com avaria'), ('INCOMPLETO', 'Incompleto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidoformulario',
            name='local_recebimento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoformulario',
            name='numero_formulario_recebimento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedidoformulario',
            name='observacao_recebimento',
            field=models.TextField(blank=True),
        ),
    ]
