# Generated by Django 5.2.8 on 2026-02-24 20:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_materiel_pilier_default_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='pilier',
            field=models.CharField(choices=[('TODOS', 'Todos os Pilares'), ('PILAR3', 'Pilar 3'), ('PILAR2', 'Pilar 2'), ('PILAR1', 'Pilar 1')], default='TODOS', help_text='Pilar auquel ce matériel est affecté', max_length=10, verbose_name=api.models.Entrepot),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero', 'date'], name='api_facture_numero_8edfa5_idx'),
        ),
    ]
