# Generated by Django 5.2.8 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_souscategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscategorie',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nome da Subcategoria'),
        ),
    ]
