# Generated by Django 5.2.8 on 2026-02-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_ped_prefix_from_demande_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='souscategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='api.souscategorie', verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='demandelot',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Rascunho'), ('EN_ATTENTE', 'Pendente'), ('APPROUVEE', 'Aprovada'), ('REFUSEE', 'Recusada'), ('LIVREE', 'Entregue'), ('RECEBIDA', 'Recebida')], default='BROUILLON', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('STOCK_BA', 'Stock Ba'), ('DEMANN_APWOUVE', 'Demann Apwouve'), ('RECEBIMENTO_PENDENTE', 'Recebimento Pendente')], max_length=20),
        ),
    ]
