# Generated by Django 5.2.8 on 2026-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_pedidoformulario_numero_formulario_saida'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_timesta_da87a7_idx',
            old_name='api_auditlo_timesta_08f2d8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_action_0a1743_idx',
            old_name='api_auditlo_action_53825f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_module_d06630_idx',
            old_name='api_auditlo_module_493273_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_model_n_792095_idx',
            old_name='api_auditlo_model_n_8f3026_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_referen_dcb217_idx',
            old_name='api_auditlo_referen_1ffbf2_idx',
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'Pendente'), ('ENTREGUE', 'Entregue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demandelot',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Rascunho'), ('EN_ATTENTE', 'Pendente'), ('APPROUVEE', 'Aprovada'), ('REFUSEE', 'Recusada'), ('ENTREGUE', 'Entregue'), ('RECEBIDA', 'Recebida')], default='BROUILLON', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='pedidoformulario',
            table='api_pedidoformulario',
        ),
    ]
