# Generated by Django 5.2.8 on 2026-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_api_auditlo_timesta_08f2d8_idx_api_auditlo_timesta_da87a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='code',
            field=models.CharField(blank=True, help_text='Code court unique dans la famille (ex: TUB, VAL, RAC)', max_length=10, null=True, verbose_name='Code Catégorie'),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='code',
            field=models.CharField(blank=True, help_text='Code court unique dans la catégorie (ex: PVC, ACR, GAL)', max_length=10, null=True, verbose_name='Code Sous-catégorie'),
        ),
    ]
