# Generated by Django 5.2.8 on 2026-06-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_code_to_categorie_souscategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='stock_inicial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Inicial'),
        ),
    ]
