# Generated by Django 5.2.8 on 2026-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_materiel_reference_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelot',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Rascunho'), ('EN_ATTENTE', 'Pendente'), ('APPROUVEE', 'Aprovada'), ('REFUSEE', 'Recusada'), ('ENTREGUE', 'Entregue'), ('RECEBIDA', 'Recebida'), ('ANNULE', 'Cancelada')], default='BROUILLON', max_length=15, verbose_name='Status'),
        ),
    ]
